spring:
  application:
    name: shopping-sys

  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_sys
    username: postgres
    password: devzeus2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # Static resources configuration
  web:
    resources:
      static-locations: classpath:/static/,file:img/

  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Image storage configuration
image:
  storage:
    path: img/
